#ifndef JESNK_H
#define JESNK_H
#define RAIL_COL 10
#define RAIL_ROW 5
#define RAIL1OFFSET RAIL_COL
#define RAIL2OFFSET RAIL_COL*3
#define NUM_STAT RAIL_COL*2+1


#define DIS_POT_1_OFFSET 4
#define DIS_RBA_1_OFFSET 3
#define DIS_RBA_2_OFFSET 5
#define DIS_RBA_3_OFFSET 9
#define DIS_POT_2_OFFSET 9

#define STAT_RAIL1OFFSET 0
#define STAT_RAIL2OFFSET RAIL_COL
#define DISP_RAIL2OFFSET RAIL_COL

#define STAT_POT1OFFSET (4)
#define STAT_POT2OFFSET (RAIL_COL+4)
#define STAT_POT3OFFSET (RAIL_COL*2) 
#define STAT_RBA1_1OFFSET 3 
#define STAT_RBA1_2OFFSET 5 
#define STAT_RBA1_3OFFSET 9
#define STAT_RBA2_1OFFSET RAIL_COL +  3 
#define STAT_RBA2_2OFFSET RAIL_COL + 5 
#define STAT_RBA2_3OFFSET RAIL_COL + 9 

#define SYBL_DIV 'X'
#define SYBL_RBA '@'



#endif // JESNK_H
